# docker-compose.yml
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
